# -*- coding: utf-8 -*-
"""
Generated by ArcGIS ModelBuilder on : 2020-10-13 16:48:02
"""
import arcpy

def cliptest():  # Clip Test Model

    # To allow overwriting outputs change overwriteOutput option to True.
    arcpy.env.overwriteOutput = False

    _0 = "https://gis-staging.usda.net/server/rest/services/Hosted/Certified_Wetland_Determinations_Test_Feature_Layer/FeatureServer/0"
    Define_AOI_in091_t0012564_2020_09 = "C:\\Determinations\\in091_t0012564_2020_09\\in091_t0012564_2020_09_BaseData.gdb\\Layers\\Define_AOI_in091_t0012564_2020_09"

    # Process: Clip (Clip) (analysis)
    portal_clipped_cwd = "C:\\GIS_Tools\\NRCS_Wetland_Tools_Pro\\SUPPORT\\Conversions.gdb\\portal_clipped_cwd"
    arcpy.analysis.Clip(in_features=_0, clip_features=Define_AOI_in091_t0012564_2020_09, out_feature_class=portal_clipped_cwd, cluster_tolerance="")

if __name__ == '__main__':
    # Global Environment settings
    with arcpy.EnvManager(scratchWorkspace=r"C:\GIS_Tools\NRCS_Wetland_Tools_Pro\SUPPORT\SCRATCH.gdb", workspace=r"C:\GIS_Tools\NRCS_Wetland_Tools_Pro\SUPPORT\SCRATCH.gdb"):
        cliptest()
